# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 4
  ParameterListWrapping:
    indentSize: 4
  NoWildcardImports:
    active: false
  SpacingAroundColon:
    active: false

style:
  ReturnCount:
    active: false
  WildcardImport:
    active: false
